// Renders a profile object into the config/profile.mjs module source.
//
// This is the security boundary for `npm run setup:profile`: the model's output
// is data, and every value is embedded with JSON.stringify, so text that looks
// like code becomes a string containing that text. Nothing the model returns is
// ever evaluated. There are no substitutions of any kind, so every field is
// exactly one JSON literal.
const literal = (value) => JSON.stringify(value);

export function renderProfile(profile) {
  return `// Generated by \`npm run setup:profile\`. Edit freely — it is yours, and it is
// gitignored. After changing anything here, redeploy:  npm run deploy
//
// See config/profile.example.mjs for what each field is for.

export const ABOUT_YOU = ${literal(profile.ABOUT_YOU)};

export const RUBRIC = ${literal(profile.RUBRIC)};

export const MUTED_SENDERS = ${JSON.stringify(profile.MUTED_SENDERS, null, 2)};

export const VOICE = ${literal(profile.VOICE)};

export const REPLY_STYLE = ${literal(profile.REPLY_STYLE)};
`;
}
